---
name: Maven

on:
- push

jobs:
  build:
    defaults:
      run:
        working-directory: ./unique-attribute-validator-provider

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      security-events: write
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java-kotlin
        queries: security-extended,security-and-quality

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven

    - name: Get AWS credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::771971951923:role/keycloak-unique-attribute-artifact-upload
        audience: sts.amazonaws.com
        role-duration-seconds: 900

    - name: Build with Maven
      run: mvn -B clean package deploy

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:java-kotlin"

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v5
      with:
        directory: ./unique-attribute-validator-provider